[project]
name = "f-tool"
version = "0.1.0"
description = "Unified file operation CLI tool with auto-mkdir and progress display"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "tqdm>=4.66.0",
    "send2trash>=1.8.0",
]

[project.scripts]
f = "f_tool.main:main"
